using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using PokemonPocket;
using Server;
using Database;

namespace Models
{
    public class User
    {
        [Key]
        public string? Id { get; set; }
        public string? Username { get; set; }
        public string? Password { get; set; }
        public string? Email { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public int Coins { get; set; }
        public bool God { get; set; } = false;
        public bool IsBanned { get; set; } = false;
        public bool InRoom { get; set; } = false;

        public bool FreePika { get; set; } = false;
        public bool FreeEevee { get; set; } = false;
        public bool FreeChar { get; set; } = false;

        // Link to Pokemon
        public virtual ICollection<PokemonMaster> Pokemon { get; set; } = new List<PokemonMaster>();
        public virtual ICollection<PokemonMaster> BattlePokemon { get; set; } = new List<PokemonMaster>();

        // Parameterless constructor for EF Core
        private User() { }

        // Instance constructor
        public User(string Username, string Password, string Email)
        {
            Id = Guid.NewGuid().ToString("N").Substring(0, 15);
            this.Username = Username;
            this.Password = Password;
            this.Email = Email;
            Wins = 0;
            Losses = 0;
            Coins = 100;

        }

        public double CalculateWinLossRatio()
        {
            if (Losses == 0) return Wins;
            return Math.Round((double)Wins / Losses, 2);
        }

        public void UpdateBattlePokemon()
        {
            BattlePokemon.Clear();

            foreach (var pm in Pokemon)
            {
                if (pm.Selected) { BattlePokemon.Add(pm); }
            }
        }

        public PokemonMaster? AssignmentGetPokemon(string name)
        {
            PokemonMaster? pokemon = name.ToLower() switch
            {
                "alakazam" => new Alakazam(Id!),
                "arbok" => new Arbok(Id!),
                "arcanine" => new Arcanine(Id!),
                "beedrill" => new Beedrill(Id!),
                "bellsprout" => new Bellsprout(Id!),
                "blastoise" => new Blastoise(Id!),
                "bulbasaur" => new Bulbasaur(Id!),
                "butterfree" => new Butterfree(Id!),
                "caterpie" => new Caterpie(Id!),
                "charizard" => new Charizard(Id!),
                "charmeleon" => new Charmeleon(Id!),
                "charmander" => new Charmander(Id!),
                "clefable" => new Clefable(Id!),
                "clefairy" => new Clefairy(Id!),
                "cloyster" => new Cloyster(Id!),
                "cubone" => new Cubone(Id!),
                "dewgong" => new Dewgong(Id!),
                "diglett" => new Diglett(Id!),
                "dodrio" => new Dodrio(Id!),
                "doduo" => new Doduo(Id!),
                "dragonair" => new Dragonair(Id!),
                "dragonite" => new Dragonite(Id!),
                "dratini" => new Dratini(Id!),
                "drowzee" => new Drowzee(Id!),
                "dugtrio" => new Dugtrio(Id!),
                "electrode" => new Electrode(Id!),
                "exeggutor" => new Exeggutor(Id!),
                "fearow" => new Fearow(Id!),
                "flareon" => new Flareon(Id!),
                "gengar" => new Gengar(Id!),
                "gloom" => new Gloom(Id!),
                "golbat" => new Golbat(Id!),
                "golduck" => new Golduck(Id!),
                "golem" => new Golem(Id!),
                "graveler" => new Graveler(Id!),
                "gyarados" => new Gyarados(Id!),
                "haunter" => new Haunter(Id!),
                "hypno" => new Hypno(Id!),
                "ivysaur" => new Ivysaur(Id!),
                "kabutops" => new Kabutops(Id!),
                "kadabra" => new Kadabra(Id!),
                "kakuna" => new Kakuna(Id!),
                "kingler" => new Kingler(Id!),
                "machamp" => new Machamp(Id!),
                "machoke" => new Machoke(Id!),
                "magneton" => new Magneton(Id!),
                "marowak" => new Marowak(Id!),
                "metapod" => new Metapod(Id!),
                "muk" => new Muk(Id!),
                "nidoking" => new Nidoking(Id!),
                "nidoqueen" => new Nidoqueen(Id!),
                "nidorina" => new Nidorina(Id!),
                "nidorino" => new Nidorino(Id!),
                "ninetales" => new Ninetales(Id!),
                "omastar" => new Omastar(Id!),
                "parasect" => new Parasect(Id!),
                "persian" => new Persian(Id!),
                "pidgeot" => new Pidgeot(Id!),
                "pidgeotto" => new Pidgeotto(Id!),
                "poliwhirl" => new Poliwhirl(Id!),
                "poliwrath" => new Poliwrath(Id!),
                "primeape" => new Primeape(Id!),
                "raichu" => new Raichu(Id!),
                "rapidash" => new Rapidash(Id!),
                "raticate" => new Raticate(Id!),
                "rhydon" => new Rhydon(Id!),
                "sandslash" => new Sandslash(Id!),
                "seadra" => new Seadra(Id!),
                "seaking" => new Seaking(Id!),
                "slowbro" => new Slowbro(Id!),
                "starmie" => new Starmie(Id!),
                "tentacruel" => new Tentacruel(Id!),
                "venomoth" => new Venomoth(Id!),
                "venusaur" => new Venusaur(Id!),
                "victreebel" => new Victreebel(Id!),
                "vileplume" => new Vileplume(Id!),
                "wartortle" => new Wartortle(Id!),
                "weepinbell" => new Weepinbell(Id!),
                "weezing" => new Weezing(Id!),
                "wigglytuff" => new Wigglytuff(Id!),
                _ => null
            };
            if (pokemon != null)
            {
                pokemon.MaxHealth = pokemon.HealthOverride;
                return pokemon;
            }
            return null;
        }

        public void GetPokemon(string name)
        {
            using (var context = new DatabaseContext())
            {
                PokemonMaster? pokemon = name.ToLower() switch
                {
                    "abra" => new Abra("None", Id!),
                    "aerodactyl" => new Aerodactyl("None", Id!),
                    "alakazam" => new Alakazam("None", Id!),
                    "arbok" => new Arbok("None", Id!),
                    "arcanine" => new Arcanine("None", Id!),
                    "articuno" => new Articuno("None", Id!),
                    "beedrill" => new Beedrill("None", Id!),
                    "bellsprout" => new Bellsprout("None", Id!),
                    "blastoise" => new Blastoise("None", Id!),
                    "bulbasaur" => new Bulbasaur("None", Id!),
                    "butterfree" => new Butterfree("None", Id!),
                    "caterpie" => new Caterpie("None", Id!),
                    "chansey" => new Chansey("None", Id!),
                    "charizard" => new Charizard("None", Id!),
                    "charmeleon" => new Charmeleon("None", Id!),
                    "charmander" => new Charmander("None", Id!),
                    "clefable" => new Clefable("None", Id!),
                    "clefairy" => new Clefairy("None", Id!),
                    "cloyster" => new Cloyster("None", Id!),
                    "cubone" => new Cubone("None", Id!),
                    "dewgong" => new Dewgong("None", Id!),
                    "diglett" => new Diglett("None", Id!),
                    "ditto" => new Ditto("None", Id!),
                    "dodrio" => new Dodrio("None", Id!),
                    "doduo" => new Doduo("None", Id!),
                    "dragonair" => new Dragonair("None", Id!),
                    "dragonite" => new Dragonite("None", Id!),
                    "dratini" => new Dratini("None", Id!),
                    "drowzee" => new Drowzee("None", Id!),
                    "dugtrio" => new Dugtrio("None", Id!),
                    "eevee" => new Eevee("None", Id!),
                    "ekans" => new Ekans("None", Id!),
                    "electabuzz" => new Electabuzz("None", Id!),
                    "electrode" => new Electrode("None", Id!),
                    "exeggcute" => new Exeggcute("None", Id!),
                    "exeggutor" => new Exeggutor("None", Id!),
                    "farfetch" => new Farfetch("None", Id!),
                    "fearow" => new Fearow("None", Id!),
                    "flareon" => new Flareon("None", Id!),
                    "gastly" => new Gastly("None", Id!),
                    "gengar" => new Gengar("None", Id!),
                    "geodude" => new Geodude("None", Id!),
                    "gloom" => new Gloom("None", Id!),
                    "golbat" => new Golbat("None", Id!),
                    "goldeen" => new Goldeen("None", Id!),
                    "golduck" => new Golduck("None", Id!),
                    "golem" => new Golem("None", Id!),
                    "graveler" => new Graveler("None", Id!),
                    "grimer" => new Grimer("None", Id!),
                    "growlithe" => new Growlithe("None", Id!),
                    "gyarados" => new Gyarados("None", Id!),
                    "haunter" => new Haunter("None", Id!),
                    "hitmonchan" => new Hitmonchan("None", Id!),
                    "hitmonlee" => new Hitmonlee("None", Id!),
                    "horsea" => new Horsea("None", Id!),
                    "hypno" => new Hypno("None", Id!),
                    "ivysaur" => new Ivysaur("None", Id!),
                    "jigglypuff" => new Jigglypuff("None", Id!),
                    "jolteon" => new Jolteon("None", Id!),
                    "jynx" => new Jynx("None", Id!),
                    "kabuto" => new Kabuto("None", Id!),
                    "kabutops" => new Kabutops("None", Id!),
                    "kadabra" => new Kadabra("None", Id!),
                    "kakuna" => new Kakuna("None", Id!),
                    "kangaskhan" => new Kangaskhan("None", Id!),
                    "kingler" => new Kingler("None", Id!),
                    "koffing" => new Koffing("None", Id!),
                    "krabby" => new Krabby("None", Id!),
                    "lapras" => new Lapras("None", Id!),
                    "lickitung" => new Lickitung("None", Id!),
                    "machamp" => new Machamp("None", Id!),
                    "machoke" => new Machoke("None", Id!),
                    "machop" => new Machop("None", Id!),
                    "magikarp" => new Magikarp("None", Id!),
                    "magmar" => new Magmar("None", Id!),
                    "magnemite" => new Magnemite("None", Id!),
                    "magneton" => new Magneton("None", Id!),
                    "mankey" => new Mankey("None", Id!),
                    "marowak" => new Marowak("None", Id!),
                    "meowth" => new Meowth("None", Id!),
                    "metapod" => new Metapod("None", Id!),
                    "mew" => new Mew("None", Id!),
                    "mewtwo" => new Mewtwo("None", Id!),
                    "moltres" => new Moltres("None", Id!),
                    "mr mime" => new MrMime("None", Id!),
                    "muk" => new Muk("None", Id!),
                    "nidoking" => new Nidoking("None", Id!),
                    "nidoqueen" => new Nidoqueen("None", Id!),
                    "nidoranf" => new NidoranF("None", Id!),
                    "nidoranm" => new NidoranM("None", Id!),
                    "nidorina" => new Nidorina("None", Id!),
                    "nidorino" => new Nidorino("None", Id!),
                    "ninetales" => new Ninetales("None", Id!),
                    "oddish" => new Oddish("None", Id!),
                    "omanyte" => new Omanyte("None", Id!),
                    "omastar" => new Omastar("None", Id!),
                    "onix" => new Onix("None", Id!),
                    "paras" => new Paras("None", Id!),
                    "parasect" => new Parasect("None", Id!),
                    "persian" => new Persian("None", Id!),
                    "pidgeot" => new Pidgeot("None", Id!),
                    "pidgeotto" => new Pidgeotto("None", Id!),
                    "pidgey" => new Pidgey("None", Id!),
                    "pikachu" => new Pikachu("None", Id!),
                    "pinsir" => new Pinsir("None", Id!),
                    "poliwag" => new Poliwag("None", Id!),
                    "poliwhirl" => new Poliwhirl("None", Id!),
                    "poliwrath" => new Poliwrath("None", Id!),
                    "ponyta" => new Ponyta("None", Id!),
                    "porygon" => new Porygon("None", Id!),
                    "primeape" => new Primeape("None", Id!),
                    "psyduck" => new Psyduck("None", Id!),
                    "raichu" => new Raichu("None", Id!),
                    "rapidash" => new Rapidash("None", Id!),
                    "raticate" => new Raticate("None", Id!),
                    "rattata" => new Rattata("None", Id!),
                    "rhydon" => new Rhydon("None", Id!),
                    "rhyhorn" => new Rhyhorn("None", Id!),
                    "sandslash" => new Sandslash("None", Id!),
                    "sandshrew" => new Sandshrew("None", Id!),
                    "scyther" => new Scyther("None", Id!),
                    "seadra" => new Seadra("None", Id!),
                    "seaking" => new Seaking("None", Id!),
                    "seel" => new Seel("None", Id!),
                    "shellder" => new Shellder("None", Id!),
                    "slowbro" => new Slowbro("None", Id!),
                    "slowpoke" => new Slowpoke("None", Id!),
                    "snorlax" => new Snorlax("None", Id!),
                    "spearow" => new Spearow("None", Id!),
                    "squirtle" => new Squirtle("None", Id!),
                    "starmie" => new Starmie("None", Id!),
                    "staryu" => new Staryu("None", Id!),
                    "tangela" => new Tangela("None", Id!),
                    "tauros" => new Tauros("None", Id!),
                    "tentacool" => new Tentacool("None", Id!),
                    "tentacruel" => new Tentacruel("None", Id!),
                    "vaporeon" => new Vaporeon("None", Id!),
                    "venomoth" => new Venomoth("None", Id!),
                    "venonat" => new Venonat("None", Id!),
                    "venusaur" => new Venusaur("None", Id!),
                    "victreebel" => new Victreebel("None", Id!),
                    "vileplume" => new Vileplume("None", Id!),
                    "voltorb" => new Voltorb("None", Id!),
                    "vulpix" => new Vulpix("None", Id!),
                    "wartortle" => new Wartortle("None", Id!),
                    "weedle" => new Weedle("None", Id!),
                    "weepinbell" => new Weepinbell("None", Id!),
                    "weezing" => new Weezing("None", Id!),
                    "wigglytuff" => new Wigglytuff("None", Id!),
                    "zapdos" => new Zapdos("None", Id!),
                    "zubat" => new Zubat("None", Id!),
                    _ => null
                };

                if (pokemon != null)
                {
                    Pokemon.Add(pokemon);
                    context.SaveChanges();
                }
                else
                {
                    Console.WriteLine($"Pokemon {name} not found.");
                }
            }
        }

        // New method for registration process
        public PokemonMaster? GetPokemonWithoutSaving(string name, string userId)
        {
            PokemonMaster? pokemon = name.ToLower().Trim() switch
            {
                "abra" => new Abra("None", userId!),
                "aerodactyl" => new Aerodactyl("None", userId!),
                "alakazam" => new Alakazam("None", userId!),
                "arbok" => new Arbok("None", userId!),
                "arcanine" => new Arcanine("None", userId!),
                "articuno" => new Articuno("None", userId!),
                "beedrill" => new Beedrill("None", userId!),
                "bellsprout" => new Bellsprout("None", userId!),
                "blastoise" => new Blastoise("None", userId!),
                "bulbasaur" => new Bulbasaur("None", userId!),
                "butterfree" => new Butterfree("None", userId!),
                "caterpie" => new Caterpie("None", userId!),
                "chansey" => new Chansey("None", userId!),
                "charizard" => new Charizard("None", userId!),
                "charmeleon" => new Charmeleon("None", userId!),
                "charmander" => new Charmander("None", userId!),
                "clefable" => new Clefable("None", userId!),
                "clefairy" => new Clefairy("None", userId!),
                "cloyster" => new Cloyster("None", userId!),
                "cubone" => new Cubone("None", userId!),
                "dewgong" => new Dewgong("None", userId!),
                "diglett" => new Diglett("None", userId!),
                "ditto" => new Ditto("None", userId!),
                "dodrio" => new Dodrio("None", userId!),
                "doduo" => new Doduo("None", userId!),
                "dragonair" => new Dragonair("None", userId!),
                "dragonite" => new Dragonite("None", userId!),
                "dratini" => new Dratini("None", userId!),
                "drowzee" => new Drowzee("None", userId!),
                "dugtrio" => new Dugtrio("None", userId!),
                "eevee" => new Eevee("None", userId!),
                "ekans" => new Ekans("None", userId!),
                "electabuzz" => new Electabuzz("None", userId!),
                "electrode" => new Electrode("None", userId!),
                "exeggcute" => new Exeggcute("None", userId!),
                "exeggutor" => new Exeggutor("None", userId!),
                "farfetch" => new Farfetch("None", userId!),
                "fearow" => new Fearow("None", userId!),
                "flareon" => new Flareon("None", userId!),
                "gastly" => new Gastly("None", userId!),
                "gengar" => new Gengar("None", userId!),
                "geodude" => new Geodude("None", userId!),
                "gloom" => new Gloom("None", userId!),
                "golbat" => new Golbat("None", userId!),
                "goldeen" => new Goldeen("None", userId!),
                "golduck" => new Golduck("None", userId!),
                "golem" => new Golem("None", userId!),
                "graveler" => new Graveler("None", userId!),
                "grimer" => new Grimer("None", userId!),
                "growlithe" => new Growlithe("None", userId!),
                "gyarados" => new Gyarados("None", userId!),
                "haunter" => new Haunter("None", userId!),
                "hitmonchan" => new Hitmonchan("None", userId!),
                "hitmonlee" => new Hitmonlee("None", userId!),
                "horsea" => new Horsea("None", userId!),
                "hypno" => new Hypno("None", userId!),
                "ivysaur" => new Ivysaur("None", userId!),
                "jigglypuff" => new Jigglypuff("None", userId!),
                "jolteon" => new Jolteon("None", userId!),
                "jynx" => new Jynx("None", userId!),
                "kabuto" => new Kabuto("None", userId!),
                "kabutops" => new Kabutops("None", userId!),
                "kadabra" => new Kadabra("None", userId!),
                "kakuna" => new Kakuna("None", userId!),
                "kangaskhan" => new Kangaskhan("None", userId!),
                "kingler" => new Kingler("None", userId!),
                "koffing" => new Koffing("None", userId!),
                "krabby" => new Krabby("None", userId!),
                "lapras" => new Lapras("None", userId!),
                "lickitung" => new Lickitung("None", userId!),
                "machamp" => new Machamp("None", userId!),
                "machoke" => new Machoke("None", userId!),
                "machop" => new Machop("None", userId!),
                "magikarp" => new Magikarp("None", userId!),
                "magmar" => new Magmar("None", userId!),
                "magnemite" => new Magnemite("None", userId!),
                "magneton" => new Magneton("None", userId!),
                "mankey" => new Mankey("None", userId!),
                "marowak" => new Marowak("None", userId!),
                "meowth" => new Meowth("None", userId!),
                "metapod" => new Metapod("None", userId!),
                "mew" => new Mew("None", userId!),
                "mewtwo" => new Mewtwo("None", userId!),
                "moltres" => new Moltres("None", userId!),
                "mr mime" => new MrMime("None", userId!),
                "muk" => new Muk("None", userId!),
                "nidoking" => new Nidoking("None", userId!),
                "nidoqueen" => new Nidoqueen("None", userId!),
                "nidoranf" => new NidoranF("None", userId!),
                "nidoranm" => new NidoranM("None", userId!),
                "nidorina" => new Nidorina("None", userId!),
                "nidorino" => new Nidorino("None", userId!),
                "ninetales" => new Ninetales("None", userId!),
                "oddish" => new Oddish("None", userId!),
                "omanyte" => new Omanyte("None", userId!),
                "omastar" => new Omastar("None", userId!),
                "onix" => new Onix("None", userId!),
                "paras" => new Paras("None", userId!),
                "parasect" => new Parasect("None", userId!),
                "persian" => new Persian("None", userId!),
                "pidgeot" => new Pidgeot("None", userId!),
                "pidgeotto" => new Pidgeotto("None", userId!),
                "pidgey" => new Pidgey("None", userId!),
                "pikachu" => new Pikachu("None", userId!),
                "pinsir" => new Pinsir("None", userId!),
                "poliwag" => new Poliwag("None", userId!),
                "poliwhirl" => new Poliwhirl("None", userId!),
                "poliwrath" => new Poliwrath("None", userId!),
                "ponyta" => new Ponyta("None", userId!),
                "porygon" => new Porygon("None", userId!),
                "primeape" => new Primeape("None", userId!),
                "psyduck" => new Psyduck("None", userId!),
                "raichu" => new Raichu("None", userId!),
                "rapidash" => new Rapidash("None", userId!),
                "raticate" => new Raticate("None", userId!),
                "rattata" => new Rattata("None", userId!),
                "rhydon" => new Rhydon("None", userId!),
                "rhyhorn" => new Rhyhorn("None", userId!),
                "sandslash" => new Sandslash("None", userId!),
                "sandshrew" => new Sandshrew("None", userId!),
                "scyther" => new Scyther("None", userId!),
                "seadra" => new Seadra("None", userId!),
                "seaking" => new Seaking("None", userId!),
                "seel" => new Seel("None", userId!),
                "shellder" => new Shellder("None", userId!),
                "slowbro" => new Slowbro("None", userId!),
                "slowpoke" => new Slowpoke("None", userId!),
                "snorlax" => new Snorlax("None", userId!),
                "spearow" => new Spearow("None", userId!),
                "squirtle" => new Squirtle("None", userId!),
                "starmie" => new Starmie("None", userId!),
                "staryu" => new Staryu("None", userId!),
                "tangela" => new Tangela("None", userId!),
                "tauros" => new Tauros("None", userId!),
                "tentacool" => new Tentacool("None", userId!),
                "tentacruel" => new Tentacruel("None", userId!),
                "vaporeon" => new Vaporeon("None", userId!),
                "venomoth" => new Venomoth("None", userId!),
                "venonat" => new Venonat("None", userId!),
                "venusaur" => new Venusaur("None", userId!),
                "victreebel" => new Victreebel("None", userId!),
                "vileplume" => new Vileplume("None", userId!),
                "voltorb" => new Voltorb("None", userId!),
                "vulpix" => new Vulpix("None", userId!),
                "wartortle" => new Wartortle("None", userId!),
                "weedle" => new Weedle("None", userId!),
                "weepinbell" => new Weepinbell("None", userId!),
                "weezing" => new Weezing("None", userId!),
                "wigglytuff" => new Wigglytuff("None", userId!),
                "zapdos" => new Zapdos("None", userId!),
                "zubat" => new Zubat("None", userId!),
                _ => null
            };

            // Return the created Pokemon for batch saving later
            return pokemon;
        }

        public PokemonMaster? AdminGetPokemon(string name, string userId, float HP, int exp)
        {
            PokemonMaster? pokemon = name.ToLower().Trim() switch
            {
                "abra" => new Abra(HP, name, userId, exp),
                "aerodactyl" => new Aerodactyl(HP, name, userId, exp),
                "alakazam" => new Alakazam(HP, name, userId, exp),
                "arbok" => new Arbok(HP, name, userId, exp),
                "arcanine" => new Arcanine(HP, name, userId, exp),
                "articuno" => new Articuno(HP, name, userId, exp),
                "beedrill" => new Beedrill(HP, name, userId, exp),
                "bellsprout" => new Bellsprout(HP, name, userId, exp),
                "blastoise" => new Blastoise(HP, name, userId, exp),
                "bulbasaur" => new Bulbasaur(HP, name, userId, exp),
                "butterfree" => new Butterfree(HP, name, userId, exp),
                "caterpie" => new Caterpie(HP, name, userId, exp),
                "chansey" => new Chansey(HP, name, userId, exp),
                "charizard" => new Charizard(HP, name, userId, exp),
                "charmeleon" => new Charmeleon(HP, name, userId, exp),
                "charmander" => new Charmander(HP, name, userId, exp),
                "clefable" => new Clefable(HP, name, userId, exp),
                "clefairy" => new Clefairy(HP, name, userId, exp),
                "cloyster" => new Cloyster(HP, name, userId, exp),
                "cubone" => new Cubone(HP, name, userId, exp),
                "dewgong" => new Dewgong(HP, name, userId, exp),
                "diglett" => new Diglett(HP, name, userId, exp),
                "ditto" => new Ditto(HP, name, userId, exp),
                "dodrio" => new Dodrio(HP, name, userId, exp),
                "doduo" => new Doduo(HP, name, userId, exp),
                "dragonair" => new Dragonair(HP, name, userId, exp),
                "dragonite" => new Dragonite(HP, name, userId, exp),
                "dratini" => new Dratini(HP, name, userId, exp),
                "drowzee" => new Drowzee(HP, name, userId, exp),
                "dugtrio" => new Dugtrio(HP, name, userId, exp),
                "eevee" => new Eevee(HP, name, userId, exp),
                "ekans" => new Ekans(HP, name, userId, exp),
                "electabuzz" => new Electabuzz(HP, name, userId, exp),
                "electrode" => new Electrode(HP, name, userId, exp),
                "exeggcute" => new Exeggcute(HP, name, userId, exp),
                "exeggutor" => new Exeggutor(HP, name, userId, exp),
                "farfetch" => new Farfetch(HP, name, userId, exp),
                "fearow" => new Fearow(HP, name, userId, exp),
                "flareon" => new Flareon(HP, name, userId, exp),
                "gastly" => new Gastly(HP, name, userId, exp),
                "gengar" => new Gengar(HP, name, userId, exp),
                "geodude" => new Geodude(HP, name, userId, exp),
                "gloom" => new Gloom(HP, name, userId, exp),
                "golbat" => new Golbat(HP, name, userId, exp),
                "goldeen" => new Goldeen(HP, name, userId, exp),
                "golduck" => new Golduck(HP, name, userId, exp),
                "golem" => new Golem(HP, name, userId, exp),
                "graveler" => new Graveler(HP, name, userId, exp),
                "grimer" => new Grimer(HP, name, userId, exp),
                "growlithe" => new Growlithe(HP, name, userId, exp),
                "gyarados" => new Gyarados(HP, name, userId, exp),
                "haunter" => new Haunter(HP, name, userId, exp),
                "hitmonchan" => new Hitmonchan(HP, name, userId, exp),
                "hitmonlee" => new Hitmonlee(HP, name, userId, exp),
                "horsea" => new Horsea(HP, name, userId, exp),
                "hypno" => new Hypno(HP, name, userId, exp),
                "ivysaur" => new Ivysaur(HP, name, userId, exp),
                "jigglypuff" => new Jigglypuff(HP, name, userId, exp),
                "jolteon" => new Jolteon(HP, name, userId, exp),
                "jynx" => new Jynx(HP, name, userId, exp),
                "kabuto" => new Kabuto(HP, name, userId, exp),
                "kabutops" => new Kabutops(HP, name, userId, exp),
                "kadabra" => new Kadabra(HP, name, userId, exp),
                "kakuna" => new Kakuna(HP, name, userId, exp),
                "kangaskhan" => new Kangaskhan(HP, name, userId, exp),
                "kingler" => new Kingler(HP, name, userId, exp),
                "koffing" => new Koffing(HP, name, userId, exp),
                "krabby" => new Krabby(HP, name, userId, exp),
                "lapras" => new Lapras(HP, name, userId, exp),
                "lickitung" => new Lickitung(HP, name, userId, exp),
                "machamp" => new Machamp(HP, name, userId, exp),
                "machoke" => new Machoke(HP, name, userId, exp),
                "machop" => new Machop(HP, name, userId, exp),
                "magikarp" => new Magikarp(HP, name, userId, exp),
                "magmar" => new Magmar(HP, name, userId, exp),
                "magnemite" => new Magnemite(HP, name, userId, exp),
                "magneton" => new Magneton(HP, name, userId, exp),
                "mankey" => new Mankey(HP, name, userId, exp),
                "marowak" => new Marowak(HP, name, userId, exp),
                "meowth" => new Meowth(HP, name, userId, exp),
                "metapod" => new Metapod(HP, name, userId, exp),
                "mew" => new Mew(HP, name, userId, exp),
                "mewtwo" => new Mewtwo(HP, name, userId, exp),
                "moltres" => new Moltres(HP, name, userId, exp),
                "mr mime" => new MrMime(HP, name, userId, exp),
                "muk" => new Muk(HP, name, userId, exp),
                "nidoking" => new Nidoking(HP, name, userId, exp),
                "nidoqueen" => new Nidoqueen(HP, name, userId, exp),
                "nidoranf" => new NidoranF(HP, name, userId, exp),
                "nidoranm" => new NidoranM(HP, name, userId, exp),
                "nidorina" => new Nidorina(HP, name, userId, exp),
                "nidorino" => new Nidorino(HP, name, userId, exp),
                "ninetales" => new Ninetales(HP, name, userId, exp),
                "oddish" => new Oddish(HP, name, userId, exp),
                "omanyte" => new Omanyte(HP, name, userId, exp),
                "omastar" => new Omastar(HP, name, userId, exp),
                "onix" => new Onix(HP, name, userId, exp),
                "paras" => new Paras(HP, name, userId, exp),
                "parasect" => new Parasect(HP, name, userId, exp),
                "persian" => new Persian(HP, name, userId, exp),
                "pidgeot" => new Pidgeot(HP, name, userId, exp),
                "pidgeotto" => new Pidgeotto(HP, name, userId, exp),
                "pidgey" => new Pidgey(HP, name, userId, exp),
                "pikachu" => new Pikachu(HP, name, userId, exp),
                "pinsir" => new Pinsir(HP, name, userId, exp),
                "poliwag" => new Poliwag(HP, name, userId, exp),
                "poliwhirl" => new Poliwhirl(HP, name, userId, exp),
                "poliwrath" => new Poliwrath(HP, name, userId, exp),
                "ponyta" => new Ponyta(HP, name, userId, exp),
                "porygon" => new Porygon(HP, name, userId, exp),
                "primeape" => new Primeape(HP, name, userId, exp),
                "psyduck" => new Psyduck(HP, name, userId, exp),
                "raichu" => new Raichu(HP, name, userId, exp),
                "rapidash" => new Rapidash(HP, name, userId, exp),
                "raticate" => new Raticate(HP, name, userId, exp),
                "rattata" => new Rattata(HP, name, userId, exp),
                "rhydon" => new Rhydon(HP, name, userId, exp),
                "rhyhorn" => new Rhyhorn(HP, name, userId, exp),
                "sandslash" => new Sandslash(HP, name, userId, exp),
                "sandshrew" => new Sandshrew(HP, name, userId, exp),
                "scyther" => new Scyther(HP, name, userId, exp),
                "seadra" => new Seadra(HP, name, userId, exp),
                "seaking" => new Seaking(HP, name, userId, exp),
                "seel" => new Seel(HP, name, userId, exp),
                "shellder" => new Shellder(HP, name, userId, exp),
                "slowbro" => new Slowbro(HP, name, userId, exp),
                "slowpoke" => new Slowpoke(HP, name, userId, exp),
                "snorlax" => new Snorlax(HP, name, userId, exp),
                "spearow" => new Spearow(HP, name, userId, exp),
                "squirtle" => new Squirtle(HP, name, userId, exp),
                "starmie" => new Starmie(HP, name, userId, exp),
                "staryu" => new Staryu(HP, name, userId, exp),
                "tangela" => new Tangela(HP, name, userId, exp),
                "tauros" => new Tauros(HP, name, userId, exp),
                "tentacool" => new Tentacool(HP, name, userId, exp),
                "tentacruel" => new Tentacruel(HP, name, userId, exp),
                "vaporeon" => new Vaporeon(HP, name, userId, exp),
                "venomoth" => new Venomoth(HP, name, userId, exp),
                "venonat" => new Venonat(HP, name, userId, exp),
                "venusaur" => new Venusaur(HP, name, userId, exp),
                "victreebel" => new Victreebel(HP, name, userId, exp),
                "vileplume" => new Vileplume(HP, name, userId, exp),
                "voltorb" => new Voltorb(HP, name, userId, exp),
                "vulpix" => new Vulpix(HP, name, userId, exp),
                "wartortle" => new Wartortle(HP, name, userId, exp),
                "weedle" => new Weedle(HP, name, userId, exp),
                "weepinbell" => new Weepinbell(HP, name, userId, exp),
                "weezing" => new Weezing(HP, name, userId, exp),
                "wigglytuff" => new Wigglytuff(HP, name, userId, exp),
                "zapdos" => new Zapdos(HP, name, userId, exp),
                "zubat" => new Zubat(HP, name, userId, exp),
                _ => null
            };
            // Return the created Pokemon for batch saving later
            return pokemon;
        }

    }
}
