// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Models.Skill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<int>("BasePower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InUse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PokemonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokemonPocket.PokemonMaster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("Attack")
                        .HasColumnType("REAL");

                    b.Property<int>("AttackIV")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Defense")
                        .HasColumnType("REAL");

                    b.Property<int>("DefenseIV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Health")
                        .HasColumnType("REAL");

                    b.Property<int>("HpIV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<float>("MaxHealth")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PokemonType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill")
                        .HasColumnType("TEXT");

                    b.Property<float>("SkillDamage")
                        .HasColumnType("REAL");

                    b.Property<string>("SkillPool")
                        .HasColumnType("TEXT");

                    b.Property<float>("SpecialAttack")
                        .HasColumnType("REAL");

                    b.Property<int>("SpecialAttackIV")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SpecialDefense")
                        .HasColumnType("REAL");

                    b.Property<int>("SpecialDefenseIV")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Speed")
                        .HasColumnType("REAL");

                    b.Property<int>("SpeedIV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PokemonMaster");

                    b.HasDiscriminator<string>("PokemonType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PokemonPocket.Abra", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Abra");
                });

            modelBuilder.Entity("PokemonPocket.Aerodactyl", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Aerodactyl");
                });

            modelBuilder.Entity("PokemonPocket.Alakazam", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Alakazam");
                });

            modelBuilder.Entity("PokemonPocket.Arbok", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Arbok");
                });

            modelBuilder.Entity("PokemonPocket.Arcanine", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Arcanine");
                });

            modelBuilder.Entity("PokemonPocket.Articuno", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Articuno");
                });

            modelBuilder.Entity("PokemonPocket.Beedrill", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Beedrill");
                });

            modelBuilder.Entity("PokemonPocket.Bellsprout", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Bellsprout");
                });

            modelBuilder.Entity("PokemonPocket.Blastoise", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Blastoise");
                });

            modelBuilder.Entity("PokemonPocket.Bulbasaur", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Bulbasaur");
                });

            modelBuilder.Entity("PokemonPocket.Butterfree", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Butterfree");
                });

            modelBuilder.Entity("PokemonPocket.Caterpie", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Caterpie");
                });

            modelBuilder.Entity("PokemonPocket.Chansey", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Chansey");
                });

            modelBuilder.Entity("PokemonPocket.Charizard", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Charizard");
                });

            modelBuilder.Entity("PokemonPocket.Charmander", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Charmander");
                });

            modelBuilder.Entity("PokemonPocket.Charmeleon", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Charmeleon");
                });

            modelBuilder.Entity("PokemonPocket.Clefable", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Clefable");
                });

            modelBuilder.Entity("PokemonPocket.Clefairy", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Clefairy");
                });

            modelBuilder.Entity("PokemonPocket.Cloyster", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Cloyster");
                });

            modelBuilder.Entity("PokemonPocket.Cubone", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Cubone");
                });

            modelBuilder.Entity("PokemonPocket.Dewgong", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Dewgong");
                });

            modelBuilder.Entity("PokemonPocket.Diglett", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Diglett");
                });

            modelBuilder.Entity("PokemonPocket.Ditto", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Ditto");
                });

            modelBuilder.Entity("PokemonPocket.Dodrio", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Dodrio");
                });

            modelBuilder.Entity("PokemonPocket.Doduo", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Doduo");
                });

            modelBuilder.Entity("PokemonPocket.Dragonair", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Dragonair");
                });

            modelBuilder.Entity("PokemonPocket.Dragonite", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Dragonite");
                });

            modelBuilder.Entity("PokemonPocket.Dratini", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Dratini");
                });

            modelBuilder.Entity("PokemonPocket.Drowzee", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Drowzee");
                });

            modelBuilder.Entity("PokemonPocket.Dugtrio", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Dugtrio");
                });

            modelBuilder.Entity("PokemonPocket.Eevee", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Eevee");
                });

            modelBuilder.Entity("PokemonPocket.Ekans", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Ekans");
                });

            modelBuilder.Entity("PokemonPocket.Electabuzz", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Electabuzz");
                });

            modelBuilder.Entity("PokemonPocket.Electrode", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Electrode");
                });

            modelBuilder.Entity("PokemonPocket.Exeggcute", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Exeggcute");
                });

            modelBuilder.Entity("PokemonPocket.Exeggutor", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Exeggutor");
                });

            modelBuilder.Entity("PokemonPocket.Farfetch", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Farfetch");
                });

            modelBuilder.Entity("PokemonPocket.Fearow", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Fearow");
                });

            modelBuilder.Entity("PokemonPocket.Flareon", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Flareon");
                });

            modelBuilder.Entity("PokemonPocket.Gastly", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Gastly");
                });

            modelBuilder.Entity("PokemonPocket.Gengar", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Gengar");
                });

            modelBuilder.Entity("PokemonPocket.Geodude", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Geodude");
                });

            modelBuilder.Entity("PokemonPocket.Gloom", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Gloom");
                });

            modelBuilder.Entity("PokemonPocket.Golbat", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Golbat");
                });

            modelBuilder.Entity("PokemonPocket.Goldeen", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Goldeen");
                });

            modelBuilder.Entity("PokemonPocket.Golduck", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Golduck");
                });

            modelBuilder.Entity("PokemonPocket.Golem", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Golem");
                });

            modelBuilder.Entity("PokemonPocket.Graveler", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Graveler");
                });

            modelBuilder.Entity("PokemonPocket.Grimer", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Grimer");
                });

            modelBuilder.Entity("PokemonPocket.Growlithe", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Growlithe");
                });

            modelBuilder.Entity("PokemonPocket.Gyarados", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Gyarados");
                });

            modelBuilder.Entity("PokemonPocket.Haunter", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Haunter");
                });

            modelBuilder.Entity("PokemonPocket.Hitmonchan", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Hitmonchan");
                });

            modelBuilder.Entity("PokemonPocket.Hitmonlee", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Hitmonlee");
                });

            modelBuilder.Entity("PokemonPocket.Horsea", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Horsea");
                });

            modelBuilder.Entity("PokemonPocket.Hypno", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Hypno");
                });

            modelBuilder.Entity("PokemonPocket.Ivysaur", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Ivysaur");
                });

            modelBuilder.Entity("PokemonPocket.Jigglypuff", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Jigglypuff");
                });

            modelBuilder.Entity("PokemonPocket.Jolteon", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Jolteon");
                });

            modelBuilder.Entity("PokemonPocket.Jynx", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Jynx");
                });

            modelBuilder.Entity("PokemonPocket.Kabuto", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Kabuto");
                });

            modelBuilder.Entity("PokemonPocket.Kabutops", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Kabutops");
                });

            modelBuilder.Entity("PokemonPocket.Kadabra", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Kadabra");
                });

            modelBuilder.Entity("PokemonPocket.Kakuna", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Kakuna");
                });

            modelBuilder.Entity("PokemonPocket.Kangaskhan", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Kangaskhan");
                });

            modelBuilder.Entity("PokemonPocket.Kingler", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Kingler");
                });

            modelBuilder.Entity("PokemonPocket.Koffing", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Koffing");
                });

            modelBuilder.Entity("PokemonPocket.Krabby", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Krabby");
                });

            modelBuilder.Entity("PokemonPocket.Lapras", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Lapras");
                });

            modelBuilder.Entity("PokemonPocket.Lickitung", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Lickitung");
                });

            modelBuilder.Entity("PokemonPocket.Machamp", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Machamp");
                });

            modelBuilder.Entity("PokemonPocket.Machoke", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Machoke");
                });

            modelBuilder.Entity("PokemonPocket.Machop", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Machop");
                });

            modelBuilder.Entity("PokemonPocket.Magikarp", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Magikarp");
                });

            modelBuilder.Entity("PokemonPocket.Magmar", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Magmar");
                });

            modelBuilder.Entity("PokemonPocket.Magnemite", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Magnemite");
                });

            modelBuilder.Entity("PokemonPocket.Magnetron", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Magnetron");
                });

            modelBuilder.Entity("PokemonPocket.Mankey", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Mankey");
                });

            modelBuilder.Entity("PokemonPocket.Marowak", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Marowak");
                });

            modelBuilder.Entity("PokemonPocket.Meowth", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Meowth");
                });

            modelBuilder.Entity("PokemonPocket.Metapod", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Metapod");
                });

            modelBuilder.Entity("PokemonPocket.Mew", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Mew");
                });

            modelBuilder.Entity("PokemonPocket.Mewtwo", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Mewtwo");
                });

            modelBuilder.Entity("PokemonPocket.Moltres", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Moltres");
                });

            modelBuilder.Entity("PokemonPocket.MrMime", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("MrMime");
                });

            modelBuilder.Entity("PokemonPocket.Muk", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Muk");
                });

            modelBuilder.Entity("PokemonPocket.Nidoking", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Nidoking");
                });

            modelBuilder.Entity("PokemonPocket.Nidoqueen", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Nidoqueen");
                });

            modelBuilder.Entity("PokemonPocket.NidoranF", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("NidoranF");
                });

            modelBuilder.Entity("PokemonPocket.NidoranM", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("NidoranM");
                });

            modelBuilder.Entity("PokemonPocket.Nidorina", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Nidorina");
                });

            modelBuilder.Entity("PokemonPocket.Nidorino", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Nidorino");
                });

            modelBuilder.Entity("PokemonPocket.Ninetales", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Ninetales");
                });

            modelBuilder.Entity("PokemonPocket.Oddish", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Oddish");
                });

            modelBuilder.Entity("PokemonPocket.Omanyte", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Omanyte");
                });

            modelBuilder.Entity("PokemonPocket.Omastar", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Omastar");
                });

            modelBuilder.Entity("PokemonPocket.Onix", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Onix");
                });

            modelBuilder.Entity("PokemonPocket.Paras", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Paras");
                });

            modelBuilder.Entity("PokemonPocket.Parasect", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Parasect");
                });

            modelBuilder.Entity("PokemonPocket.Persian", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Persian");
                });

            modelBuilder.Entity("PokemonPocket.Pidgeot", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Pidgeot");
                });

            modelBuilder.Entity("PokemonPocket.Pidgeotto", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Pidgeotto");
                });

            modelBuilder.Entity("PokemonPocket.Pidgey", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Pidgey");
                });

            modelBuilder.Entity("PokemonPocket.Pikachu", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Pikachu");
                });

            modelBuilder.Entity("PokemonPocket.Pinsir", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Pinsir");
                });

            modelBuilder.Entity("PokemonPocket.Poliwag", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Poliwag");
                });

            modelBuilder.Entity("PokemonPocket.Poliwhirl", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Poliwhirl");
                });

            modelBuilder.Entity("PokemonPocket.Poliwrath", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Poliwrath");
                });

            modelBuilder.Entity("PokemonPocket.Ponyta", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Ponyta");
                });

            modelBuilder.Entity("PokemonPocket.Porygon", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Porygon");
                });

            modelBuilder.Entity("PokemonPocket.Primeape", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Primeape");
                });

            modelBuilder.Entity("PokemonPocket.Psyduck", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Psyduck");
                });

            modelBuilder.Entity("PokemonPocket.Raichu", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Raichu");
                });

            modelBuilder.Entity("PokemonPocket.Rapidash", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Rapidash");
                });

            modelBuilder.Entity("PokemonPocket.Raticate", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Raticate");
                });

            modelBuilder.Entity("PokemonPocket.Rattata", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Rattata");
                });

            modelBuilder.Entity("PokemonPocket.Rhydon", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Rhydon");
                });

            modelBuilder.Entity("PokemonPocket.Rhyhorn", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Rhyhorn");
                });

            modelBuilder.Entity("PokemonPocket.Sandshrew", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Sandshrew");
                });

            modelBuilder.Entity("PokemonPocket.Sandslash", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Sandslash");
                });

            modelBuilder.Entity("PokemonPocket.Scyther", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Scyther");
                });

            modelBuilder.Entity("PokemonPocket.Seadra", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Seadra");
                });

            modelBuilder.Entity("PokemonPocket.Seaking", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Seaking");
                });

            modelBuilder.Entity("PokemonPocket.Seel", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Seel");
                });

            modelBuilder.Entity("PokemonPocket.Shellder", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Shellder");
                });

            modelBuilder.Entity("PokemonPocket.Slowbro", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Slowbro");
                });

            modelBuilder.Entity("PokemonPocket.Slowpoke", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Slowpoke");
                });

            modelBuilder.Entity("PokemonPocket.Snorlax", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Snorlax");
                });

            modelBuilder.Entity("PokemonPocket.Spearow", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Spearow");
                });

            modelBuilder.Entity("PokemonPocket.Squirtle", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Squirtle");
                });

            modelBuilder.Entity("PokemonPocket.Starmie", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Starmie");
                });

            modelBuilder.Entity("PokemonPocket.Staryu", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Staryu");
                });

            modelBuilder.Entity("PokemonPocket.Tangela", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Tangela");
                });

            modelBuilder.Entity("PokemonPocket.Tauros", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Tauros");
                });

            modelBuilder.Entity("PokemonPocket.Tentacool", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Tentacool");
                });

            modelBuilder.Entity("PokemonPocket.Tentacruel", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Tentacruel");
                });

            modelBuilder.Entity("PokemonPocket.Vaporeon", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Vaporeon");
                });

            modelBuilder.Entity("PokemonPocket.Venomoth", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Venomoth");
                });

            modelBuilder.Entity("PokemonPocket.Venonat", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Venonat");
                });

            modelBuilder.Entity("PokemonPocket.Venusaur", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Venusaur");
                });

            modelBuilder.Entity("PokemonPocket.Victreebel", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Victreebel");
                });

            modelBuilder.Entity("PokemonPocket.Vileplume", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Vileplume");
                });

            modelBuilder.Entity("PokemonPocket.Voltorb", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Voltorb");
                });

            modelBuilder.Entity("PokemonPocket.Vulpix", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Vulpix");
                });

            modelBuilder.Entity("PokemonPocket.Wartortle", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Wartortle");
                });

            modelBuilder.Entity("PokemonPocket.Weedle", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Weedle");
                });

            modelBuilder.Entity("PokemonPocket.Weepinbell", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Weepinbell");
                });

            modelBuilder.Entity("PokemonPocket.Weezing", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Weezing");
                });

            modelBuilder.Entity("PokemonPocket.Wigglytuff", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Wigglytuff");
                });

            modelBuilder.Entity("PokemonPocket.Zapdos", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Zapdos");
                });

            modelBuilder.Entity("PokemonPocket.Zubat", b =>
                {
                    b.HasBaseType("PokemonPocket.PokemonMaster");

                    b.HasDiscriminator().HasValue("Zubat");
                });

            modelBuilder.Entity("Models.Skill", b =>
                {
                    b.HasOne("PokemonPocket.PokemonMaster", "Pokemon")
                        .WithMany("Skills")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonPocket.PokemonMaster", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
